version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: client_service
      POSTGRES_PASSWORD: client_service
      POSTGRES_DB: client_service
      PGDATA: /tmp
    volumes:
          - ./src/main/resources/db/migration:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U client_service"]
      interval: 2s
      timeout: 3s
      retries: 30